### ISSUE TITLE
User Stats

### ISSUE THREAD

**Issue by Bobsters986** [Inner-Worlds/inner_worlds_be#21]
**Non-graphical:**
Current Streak:
Longest Streak:
Dreams Recorded THIS MONTH:
Dreams Recorded THIS WEEK (Sunday to Sunday):
Total Dreams Recorded:
Average Lucidity: 

**Graphical:**
All Time
Top 5 Emotions Pie +  Chart of Emotions 5 most popular and percentage to first decimal.
Top 5 Tags + Pie Chart of Tag 5 most popular and percentage to first decimal.

**Comment by sandfortw** [comment]
Sam:
Dreams Recorded THIS MONTH:
Dreams Recorded THIS WEEK (Sunday to Sunday)

Kassi:
Total Dreams Recorded
Average Lucidity

Jade:
All Time
Top 5 Emotions Pie + Chart of Emotions 5 most popular and percentage to first decimal.
Top 5 Tags + Pie Chart of Tag 5 most popular and percentage to first decimal.


Weston: 
Current Streak:
Longest Streak:

**Comment by Bobsters986** [comment]
- Sam:

- [ ] Dreams Recorded THIS MONTH:

- [ ] Dreams Recorded THIS WEEK (Sunday to Sunday)

- Kassi:

- [ ] Total Dreams Recorded

- [ ] Average Lucidity

- Jade + BOBBY:
All Time

- [ ] Top 5 Emotions Pie + Chart of Emotions 5 most popular and percentage to first decimal.

- [ ] Top 5 Tags + Pie Chart of Tag 5 most popular and percentage to first decimal.

- Weston:

- [ ] Current Streak:

- [ ] Longest Streak:
